### ISSUE TITLE
Error when downloading the public linelist

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/NCoVUtils#100]
It looks like the upstream owners of the linelist have moved over to using LFS and this has broken our download. @sophiemeakin I assume your pull request is also impacted by this? Is there any way you could fix this there so we can merge all at once? 

Pretty high priority on this as can't update the site without this data (and it has now been 3 days :()

I see the following: 

```
> NCoVUtils::get_international_linelist() 
Downloading linelist data
Error: Column `travel_history_location` must be length 2 (the number of rows) or one, not 0
> NCoVUtils::get_international_linelist(clean = FALSE)
Downloading linelist data
# A tibble: 2 x 1
  `version https://git-lfs.github.com/spec/v1`                               
  <chr>                                                                      
1 oid sha256:754c08d1e213356d32b9589199e867c05e5dee18e20c64eca6e68a6d73bb7a5a
2 size 115537279             
```

**Comment by tanaytrivedi** [comment]
Enough of us complained and they put up a gzipped CSV now instead of just LFS https://github.com/beoutbreakprepared/nCoV2019/issues/63. should be a little easier to use.

**Comment by seabbs** [comment]
Fantastic thanks for flagging this!
