### ISSUE TITLE
Google sheets url has changed to a github repo

### ISSUE THREAD

**Issue by jhellewell14** [epiforecasts/NCoVUtils#18]
Google sheet now redirects to: https://github.com/beoutbreakprepared/nCoV2019/

Amend url to fetch from.

**Comment by seabbs** [comment]
have they standardized where they put the data now? I looked at using their GitHub version before and they kept moving the latest version around and changing its name.

**Comment by jhellewell14** [comment]
https://github.com/beoutbreakprepared/nCoV2019/blob/master/latest_data/latestdata.csv

**Comment by seabbs** [comment]
History indicates they are now being consistent. Should be able to stop falling back to our cached version now?

**Comment by jhellewell14** [comment]
Addressed in #19

**Comment by seabbs** [comment]
Merged - ty
