### ISSUE TITLE
ECDC downlink Excel link broken

### ISSUE THREAD

**Issue by dmuijen** [epiforecasts/NCoVUtils#20]
```NCoVUtils::get_ecdc_cases``` is throwing an error as the Excel sheet can't be found. ecdc changed the download link?  (or the file is corrupted, not sure). Might as well just fetch the latest CSV instead? see below
```
trying URL 'http://www.ecdc.europa.eu/sites/default/files/documents/COVID-19-geographic-disbtribution-worldwide-2020-03-26.xls'
trying URL 'http://www.ecdc.europa.eu/sites/default/files/documents/COVID-19-geographic-disbtribution-worldwide-2020-03-26.xlsx'
trying URL 'http://www.ecdc.europa.eu/sites/default/files/documents/COVID-19-geographic-disbtribution-worldwide-2020-03-25.xls'
Error: `path` does not exist: ‘C:\Users\asdf\AppData\Local\Temp\RtmpWIIZSo/COVID-19-geographic-disbtribution-worldwide-2020-03-25.xlsx’
``` 

```
get_ecdc_cases <- function (countries = NULL) 
{
  # Get latest update
  base_url <- "https://www.ecdc.europa.eu/sites/default/files/documents/COVID-19-geographic-disbtribution-worldwide.csv"
  d <- readr::read_csv(base_url) %>% 
    dplyr::mutate(date = as.Date(DateRep, format = "%d/%m/%Y")) %>% 
    rename(geoid = GeoId, country = `Countries and territories`,
           cases = Cases, death = Deaths,
           population_2018 = 'Pop_Data.2018') %>%
    select(-DateRep) %>%
    dplyr::arrange(date) %>% dplyr::mutate(cases = ifelse(cases < 
                                                            0, 0, cases))
  if (!is.null(countries)) {
    d <- d %>% dplyr::filter(country %in% countries)
  }
  return(d)
}
```

**Comment by seabbs** [comment]
It looks like the file format has changed. Do you have a working URL?

**Comment by dmuijen** [comment]
The separate files for each day seem to be removed. Latest Excel is found here: https://www.ecdc.europa.eu/sites/default/files/documents/COVID-19-geographic-disbtribution-worldwide.xlsx 

But since there is the CSV as well thought that might be easier, see example above.

**Comment by seabbs** [comment]
Awesome thanks (we and by that I mean @kathsherratt) are on it!

**Comment by seabbs** [comment]
Thanks for identifying this and essentially solving!

In the future, we are very happy to take pull requests for things like this (no contributing guide yet to make that clear :() if you have the capacity. All pretty at capacity here.

**Comment by dmuijen** [comment]
Thanks, will do!
