### ISSUE TITLE
get_linelist url is out of date

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/NCoVUtils#44]
NCoVUtils::get_linelist()
Parsed with column specification:
cols(
  `Due to computational limitations we migrated our data to the link below. Should you have any questions please do get in touch.` = col_character(),
  X2 = col_character(),
  X3 = col_character()
)
Error in open.connection(con, "rb") : HTTP error 400.
In addition: Warning message:
Missing column names filled in: 'X2' [2], 'X3' [3] 
>

**Comment by hamishgibbs** [comment]
I will check this out. Both links are currently failing but a new datasource may be available.

**Comment by seabbs** [comment]
Fixed by @hamishgibbs
