### ISSUE TITLE
get_japan_regional_cases data source

### ISSUE THREAD

**Issue by hamishgibbs** [epiforecasts/NCoVUtils#47]
Looks like the wikipedia article has changed formats and no longer includes case counts?

https://en.wikipedia.org/wiki/2020_coronavirus_pandemic_in_Japan

**Comment by kathsherratt** [comment]
Thank you for flagging this, I'm working on this now, with data from here: 
[https://mhlw-gis.maps.arcgis.com/apps/opsdashboard/index.html#/0c5d0502bbb54f9a8dddebca003631b8](url)

**Comment by seabbs** [comment]
Done by @kathsherratt - nice (you can link issues to GitHub pull requests so they close automatically when the pull request is merged -> see right hand of page)
