### ISSUE TITLE
Germany regional data not updated since the 10th

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/NCoVUtils#85]
Just running an Rt analysis (https://epiforecasts.io/covid/) and it looks like regional cases in Germany haven't updated since the 10th. This could be a problem with the data source or staff/volunteer breaking for easter.

**Comment by kathsherratt** [comment]
Looks like we are missing data on the 9th and 11-13th. It was not updated due to Easter, explained in [this issue on the source repo](https://github.com/jgehrcke/covid-19-germany-gae/issues/93). I can't see a way around this right now, but data are being updated as of today (14th).

**Comment by seabbs** [comment]
Damn. Does this mean we will never have the data for the 9th and 11-13th?

**Comment by seabbs** [comment]
It looks like the source repo maybe applying some cleaning to the data. This may mean we want to move sources as we then layer our own cleaning on top. What do you think?

**Comment by kathsherratt** [comment]
Hmm. I don't think the source repo is cleaning the data, but if I am reading it correctly, then it is pulling from different sources.

The main data source is the Robert Koch Institute. A few things I gathered about the RKI data:
1. This is probably the best/official data source
2. They update "old" case counts as "new" confirmations come in
3. The RKI data are complete - they do include counts on our currently missing Easter days
4. But data lag a couple of days - eg as of today, there is only data up to the 12th. 

From the source repo we are using, the data we get ("data.csv") pulls from RKI plus a crowdsourced dataset ("Gesundheitsaemter by Risklayer, ZEIT ONLINE"). This means it is incomplete (missing those 3 Easter days), but current (up to today).

So I think it's a trade-off between using the most consistent/dependable data, but lagging behind a couple of days. If that's acceptable, then happy to re-write our script to switch over to the RKI data which we know will be consistent. If not then might be best to leave as is?

**Comment by seabbs** [comment]
Done by @kathsherratt
